image: python:3.9-slim

stages:
  - test
  - deploy

before_script:
  - python -m pip install -r _jb/requirements.txt
  - jupyter-book build docs

test:
  stage: test
  except:
  - main
  script:
  - echo "Test completed."

pages:
  stage: deploy
  only:
  - main
  script:
  - mv docs/_build/html public
  - apt-get update -qq && apt-get install gzip brotli -y
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
