name = "MitochondrialDynamics"
uuid = "1a231dcf-63c2-466e-8f46-4027ba595b90"
authors = ["Wen-Wei Tseng <sosiristseng@gmail.com>"]
version = "0.7.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"

[compat]
ComponentArrays = "0.15.24"
CondaPkg = "0.2.23"
DiffEqCallbacks = "4.0.0"
NaNMath = "1.0.2"
OrdinaryDiffEq = "6.89.0"
PythonCall = "0.9.23"
PythonPlot = "1.0.5"
SimpleUnPack = "1.1.0"
SteadyStateDiffEq = "2.4.1"

[preferences.CondaPkg]
backend = "Null"
offline = true
